plugins {
    id 'com.android.library'
    id 'kotlin-android'
}

def androidSourcesDir = project.projectDir.parentFile.toString()

android {
    namespace 'net.touchcapture.qr.flutterqr'
    compileSdkVersion 34

    defaultConfig {
        minSdkVersion 20
        targetSdkVersion 34
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }

    sourceSets {
        main.java.srcDirs += "$androidSourcesDir/src/main/kotlin"
    }

    buildFeatures {
        buildConfig true
    }
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'com.journeyapps:zxing-android-embedded:4.3.0'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.core:core-ktx:1.10.1'
}
